'use client'

import Link from 'next/link'
import { ArrowRight, Check, ChevronRight, Gift, HardHat, Package, ShieldCheck, Sparkles, Truck, Wrench } from 'lucide-react'
import { SiteHeader } from './site-header'

const categories = [
  ['01', 'Office & Stationery Supplies', 'Everyday office essentials, printing supplies, desk accessories, and customised stationery solutions.', '/images/products/office-stationery.png', 'Office stationery, writing instruments, printing paper and desk supplies', Package],
  ['02', 'Housekeeping & Hygiene', 'Cleaning products, washroom essentials, sanitation supplies, and workplace hygiene solutions.', '/images/products/hygiene.png', 'Cleaning products, washroom hygiene and pantry essentials', Sparkles],
  ['03', 'PPE & Workplace Safety', 'Personal protective equipment, safety signage, traffic safety, and emergency response products.', '/images/products/ppe-safety.png', 'Protective equipment, safety signage, emergency and first aid products', ShieldCheck],
  ['04', 'Fire Safety', 'Fire extinguishers, alarms, detectors, hydrants, emergency lighting, and evacuation products.', '/images/products/fire-safety.png', 'Fire extinguishers, alarms, detectors and emergency lighting', HardHat],
  ['05', 'Office Furniture', 'Workstations, office chairs, executive cabins, conference rooms, reception, cafeteria, and storage solutions.', '/images/products/office-furniture.png', 'Workstations, ergonomic seating, cabins, boardrooms and storage', Wrench],
  ['06', 'Workplace Infrastructure', 'Office interiors, partitions, workspace planning, branding, signage, and facility solutions.', '/images/products/workplace-infrastructure.png', 'Office interiors, partitions, acoustic solutions and signage', Package],
  ['07', 'Hardware & Maintenance', 'Tools, maintenance materials, electrical and plumbing supplies, and facility support products.', '/images/products/hardware-maintenance.png', 'Tools, fasteners, electrical, plumbing and maintenance supplies', Wrench],
  ['08', 'Packaging & Logistics', 'Packaging materials, shipping supplies, warehousing support, and operational consumables.', '/images/products/packaging.png', 'Boxes, tape, stretch film, protective packaging and shipping supplies', Truck],
  ['09', 'Corporate Gifts & Promotional Products', 'Employee kits, executive gifts, branded merchandise, event giveaways, and festive hampers.', '/images/products/corporate-gifting.png', 'Employee kits, executive gifts, branded merchandise and hampers', Gift],
  ['10', 'Business Support Services', 'Logistics, travel assistance, transportation coordination, and operational support services.', '/images/products/business-support.png', 'Logistics, travel, transportation and operational coordination', Truck],
] as const

const featured = [
  { eyebrow: 'Featured category 01', title: 'Office & Stationery Supplies', subtitle: 'Everything Your Workplace Needs', copy: 'We simplify office procurement with reliable sourcing, recurring supply programs, and customised stationery solutions.', groups: [['Office Essentials', 'Notebooks & Registers', 'Pens & Writing Instruments', 'Markers & Highlighters', 'Files & Folders', 'Envelopes & Labels', 'Staplers & Punches', 'Adhesives & Tapes', 'Desk Organisers'], ['Printing & Desk Supplies', 'Copier & Printer Paper', 'Printer Consumables', 'Sticky Notes', 'Writing Pads', 'Calculators', 'Desk Accessories'], ['Corporate Procurement', 'Bulk Supply Contracts', 'Recurring Supply Programs', 'Customised Stationery', 'Institutional Requirements']] },
  { eyebrow: 'Featured category 02', title: 'Housekeeping & Hygiene', subtitle: 'Clean. Hygienic. Workplace Ready.', copy: 'Maintain healthy and productive workplaces with dependable housekeeping and hygiene solutions.', groups: [['Cleaning Supplies', 'Surface & Floor Cleaners', 'Disinfectants', 'Mops & Brushes', 'Cleaning Accessories', 'Garbage Bags', 'Waste Bins'], ['Washroom & Hygiene', 'Hand Wash', 'Sanitizers', 'Tissue Rolls', 'Paper Towels', 'Air Fresheners', 'Hygiene Dispensers'], ['Pantry Essentials', 'Disposable Cups', 'Plates & Cutlery', 'Pantry Consumables', 'Pantry Cleaning Supplies']] },
  { eyebrow: 'Featured category 03', title: 'PPE & Workplace Safety', subtitle: 'Protect People. Build Safer Workplaces.', copy: 'Comprehensive safety solutions for industrial, warehouse, construction, manufacturing, and office environments.', groups: [['Personal Protective Equipment', 'Safety Helmets', 'Safety Gloves', 'Safety Shoes', 'Safety Glasses', 'Face Shields', 'Respirators & Masks', 'Safety Harnesses', 'Hi-Visibility Vests'], ['Workplace Safety', 'Safety Barricades', 'Cones & Bollards', 'Warning Signage', 'Floor Marking Tapes', 'Traffic Mirrors', 'Anti-Slip Solutions'], ['Emergency Preparedness', 'First Aid Kits', 'Eye Wash Stations', 'Emergency Stretchers', 'AEDs', 'Rescue Equipment']] },
]

const industries = ['Information Technology', 'Manufacturing', 'Healthcare & Hospitals', 'BFSI', 'Logistics & Warehousing', 'Education', 'Retail & E-Commerce', 'Hospitality', 'Commercial Real Estate', 'Startups', 'Corporate Offices', 'Government Organisations']
const process = [['01', 'Understand', 'Requirements & workspace goals'], ['02', 'Plan', 'Layouts, specifications & optimisation'], ['03', 'Supply', 'Procurement & sourcing'], ['04', 'Install', 'Professional implementation'], ['05', 'Support', 'Ongoing maintenance & assistance']]
const reasons = ['Extensive Product Portfolio', 'Tailored Business Solutions', 'Custom Procurement Support', 'Supply & Installation', 'Dedicated Customer Support']

export function ProductsPage() {
  return <main className="min-h-screen bg-black text-foreground selection:bg-primary selection:text-white">
    <SiteHeader />
    <section className="relative isolate overflow-hidden border-b border-primary/15"><div className="products-grid absolute inset-0 opacity-60" aria-hidden="true" /><div className="pointer-events-none absolute -right-56 -top-44 size-[36rem] rounded-full bg-primary/15 blur-3xl" aria-hidden="true" /><div className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><p className="text-sm font-bold uppercase tracking-[0.24em] text-primary/65">VeriForm Business Solutions</p><h1 className="mt-6 max-w-5xl text-balance text-5xl font-bold leading-[0.95] tracking-[-0.07em] text-primary sm:text-7xl lg:text-8xl">One Partner.<br /><span className="text-white">Complete Business Solutions.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-primary/70">From office supplies and workplace infrastructure to safety equipment, corporate gifting, and business support services, VeriForm helps organisations streamline procurement through a single trusted partner.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-semibold uppercase tracking-[0.12em] text-primary/70"><span>Procurement</span><span>•</span><span>Workplace Infrastructure</span><span>•</span><span>Safety</span><span>•</span><span>Furniture</span><span>•</span><span>Corporate Gifting</span></div><div className="mt-10 flex flex-wrap gap-3"><a href="#categories" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-black hover:brightness-110">Explore Products <ArrowRight data-icon="inline-end" /></a><Link href="/#quote" className="inline-flex items-center gap-2 rounded-full border border-primary/40 px-6 py-3.5 text-sm font-bold text-primary hover:bg-primary/10">Request a Quote</Link></div></div></section>
    <section id="categories" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Product categories</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Products & Solutions for Every Business Need</h2><p className="mt-6 text-base leading-7 text-primary/65">Explore our comprehensive range of products and workplace solutions designed to support everyday operations, business growth, and employee productivity.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([number, title, text, image, imageAlt, Icon]) => <article key={title} className="group overflow-hidden rounded-2xl border border-primary/15 bg-card transition hover:-translate-y-1 hover:border-primary/45"><div className="relative aspect-[16/9] overflow-hidden"><img src={image} alt={imageAlt} className="size-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" /><span className="absolute bottom-4 left-4 flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-lg"><Icon /></span><span className="absolute right-4 top-4 text-xs font-bold tracking-[0.18em] text-white/75">{number}</span></div><div className="p-6"><h3 className="text-xl font-bold text-foreground">{title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-muted-foreground">{text}</p><a href="#featured" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">View {title.includes('Infrastructure') ? 'Solutions' : title.includes('Support') ? 'Services' : 'Products'} <ChevronRight data-icon="inline-end" /></a></div></article>)}</div></section>
    <section id="featured" className="border-y border-primary/15 bg-[#07111f] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Featured solutions</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Built for the work behind the work.</h2></div><div className="mt-14 flex flex-col gap-8">{featured.map((feature) => <article key={feature.title} className="rounded-3xl border border-primary/20 bg-black p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary/55">{feature.eyebrow}</p><h3 className="mt-4 text-3xl font-bold text-primary sm:text-4xl">{feature.title}</h3><p className="mt-2 text-xl text-white">{feature.subtitle}</p><p className="mt-5 max-w-2xl leading-7 text-primary/65">{feature.copy}</p><div className="mt-8 grid gap-7 md:grid-cols-3">{feature.groups.map((group) => <div key={group[0]}><h4 className="font-bold text-white">{group[0]}</h4><ul className="mt-4 flex flex-col gap-2 text-sm text-primary/65">{group.slice(1).map((item) => <li key={item} className="flex items-start gap-2"><Check className="mt-0.5 shrink-0 text-primary" data-icon="inline-start" />{item}</li>)}</ul></div>)}</div></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Corporate gifting</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Make Every Gift a Brand Experience</h2><p className="mt-6 leading-7 text-primary/65">From employee onboarding kits to executive gifting and festive campaigns, we deliver customised corporate gifting solutions that strengthen your brand.</p><a href="#quote" className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-black">Explore Corporate Gifts <ArrowRight data-icon="inline-end" /></a></div><div className="grid gap-px overflow-hidden rounded-2xl border border-primary/20 bg-primary/20 sm:grid-cols-2">{['Employee Welcome Kits', 'Executive Gifts', 'Promotional Merchandise', 'Technology Gifts', 'Festival Gifting', 'Awards & Recognition'].map((item) => <div key={item} className="flex min-h-32 items-end bg-black p-6 text-xl font-bold text-primary transition hover:bg-[#06170b]">{item}</div>)}</div></div></section>
    <section className="border-y border-primary/15 bg-[#07111f] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Workplace infrastructure</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Creating Workspaces That Work Better</h2><p className="mt-6 leading-7 text-primary/65">End-to-end office infrastructure solutions designed around productivity, functionality, and brand identity.</p></div><div><div className="grid gap-3 sm:grid-cols-2">{['Office Interior Solutions', 'Workspace Planning', 'Glass Partitions', 'Drywall Installations', 'Acoustic Solutions', 'Corporate Signage', 'Brand Graphics', 'Fire Safety Integration', 'AMC Support'].map((item) => <div key={item} className="border border-primary/15 bg-black p-4 font-semibold text-primary">{item}</div>)}</div><div className="mt-10 grid gap-4 sm:grid-cols-5">{process.map(([number, title, text]) => <div key={number} className="border-t border-primary/40 pt-4"><span className="text-xs font-bold text-primary/50">{number}</span><h3 className="mt-3 font-bold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-primary/60">{text}</p></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Industries we serve</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Supporting Businesses Across India</h2></div><div className="grid gap-3 sm:grid-cols-2">{industries.map((industry) => <div key={industry} className="rounded-xl border border-primary/15 bg-primary/[0.04] p-5 font-semibold text-primary transition hover:border-primary/50 hover:bg-primary/10">{industry}</div>)}</div></div></section>
    <section className="border-y border-primary/15 bg-[#07111f] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Why VeriForm Business Solutions?</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">One Partner. Complete Business Solutions.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{reasons.map((reason) => <div key={reason} className="border border-primary/20 bg-black p-6"><Check className="text-primary" /><h3 className="mt-8 font-bold text-white">{reason}</h3><p className="mt-3 text-sm leading-6 text-primary/60">Source products and support through one dependable partner.</p></div>)}</div></div></section>
    <section className="px-5 py-24 text-center sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary/65">Let&apos;s build better business operations together.</p><h2 className="mt-5 text-4xl font-bold tracking-[-0.06em] text-primary sm:text-6xl">Looking for products, furniture, safety solutions or corporate gifts?</h2><p className="mx-auto mt-6 max-w-2xl leading-7 text-primary/65">Tell us your requirement and our team will recommend suitable products, configurations, and supply options.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><Link href="/#quote" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-black">Request a Quote <ArrowRight data-icon="inline-end" /></Link><Link href="/#contact" className="inline-flex items-center gap-2 rounded-full border border-primary/40 px-6 py-3.5 text-sm font-bold text-primary">Talk to Our Team</Link></div><p className="mt-10 text-sm text-primary/65">+91 82777 62051 &nbsp; • &nbsp; info@veriform.in &nbsp; • &nbsp; www.veriform.in</p></div></section>
    <footer className="border-t border-primary/15 px-5 py-8 text-center text-xs text-primary/45 sm:px-8">© 2026 VeriForm Business Solutions. One Partner. Complete Business Solutions.</footer>
  </main>
}
